// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addIncidentUpdate = `-- name: AddIncidentUpdate :one
INSERT INTO incident_updates (incident_id, status, body)
VALUES ($1, $2, $3)
RETURNING id, incident_id, status, body, created_at
`

type AddIncidentUpdateParams struct {
	IncidentID uuid.UUID `json:"incident_id"`
	Status     string    `json:"status"`
	Body       string    `json:"body"`
}

func (q *Queries) AddIncidentUpdate(ctx context.Context, arg AddIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRowContext(ctx, addIncidentUpdate, arg.IncidentID, arg.Status, arg.Body)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (org_id, title, status, severity, started_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, title, status, severity, started_at, resolved_at, created_at, updated_at
`

type CreateIncidentParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	Severity  string    `json:"severity"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, createIncident,
		arg.OrgID,
		arg.Title,
		arg.Status,
		arg.Severity,
		arg.StartedAt,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, org_id, title, status, severity, started_at, resolved_at, created_at, updated_at
FROM incidents
WHERE id = $1 AND org_id = $2
`

type GetIncidentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetIncident(ctx context.Context, arg GetIncidentParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, getIncident, arg.ID, arg.OrgID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, org_id, title, status, severity, started_at, resolved_at, created_at, updated_at
FROM incidents
WHERE org_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListIncidents(ctx context.Context, orgID uuid.UUID) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, listIncidents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :exec
UPDATE incidents
SET status      = $1,
    resolved_at = $2
WHERE id = $3 AND org_id = $4
`

type UpdateIncidentStatusParams struct {
	Status     string       `json:"status"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
	ID         uuid.UUID    `json:"id"`
	OrgID      uuid.UUID    `json:"org_id"`
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIncidentStatus,
		arg.Status,
		arg.ResolvedAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}
