// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthUser struct {
	ID uuid.UUID `json:"id"`
}

type CheckResult struct {
	ID         int64          `json:"id"`
	ServiceID  uuid.UUID      `json:"service_id"`
	OrgID      uuid.UUID      `json:"org_id"`
	CheckedAt  time.Time      `json:"checked_at"`
	Ok         bool           `json:"ok"`
	StatusCode sql.NullInt32  `json:"status_code"`
	ResponseMs sql.NullInt32  `json:"response_ms"`
	Error      sql.NullString `json:"error"`
}

type Incident struct {
	ID         uuid.UUID    `json:"id"`
	OrgID      uuid.UUID    `json:"org_id"`
	Title      string       `json:"title"`
	Status     string       `json:"status"`
	Severity   string       `json:"severity"`
	StartedAt  time.Time    `json:"started_at"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type IncidentService struct {
	IncidentID uuid.UUID `json:"incident_id"`
	ServiceID  uuid.UUID `json:"service_id"`
}

type IncidentUpdate struct {
	ID         uuid.UUID `json:"id"`
	IncidentID uuid.UUID `json:"incident_id"`
	Status     string    `json:"status"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
}

type Org struct {
	ID               uuid.UUID      `json:"id"`
	Slug             string         `json:"slug"`
	Name             string         `json:"name"`
	Plan             string         `json:"plan"`
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type OrgMember struct {
	OrgID     uuid.UUID `json:"org_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	IsDefault bool      `json:"is_default"`
}

type Service struct {
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
	Name            string    `json:"name"`
	Url             string    `json:"url"`
	Method          string    `json:"method"`
	ExpectedStatus  int32     `json:"expected_status"`
	IntervalSeconds int32     `json:"interval_seconds"`
	TimeoutSeconds  int32     `json:"timeout_seconds"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
