// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (slug, name, plan)
VALUES ($1, $2, $3)
RETURNING id, slug, name, plan, stripe_customer_id, created_at, updated_at
`

type CreateOrgParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Plan string `json:"plan"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRowContext(ctx, createOrg, arg.Slug, arg.Name, arg.Plan)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, slug, name, plan, stripe_customer_id, created_at, updated_at
FROM orgs
WHERE slug = $1
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgsForUser = `-- name: GetOrgsForUser :many
SELECT o.id, o.slug, o.name, o.plan, o.stripe_customer_id, o.created_at, o.updated_at
FROM orgs o
JOIN org_members om ON om.org_id = o.id
WHERE om.user_id = $1
`

func (q *Queries) GetOrgsForUser(ctx context.Context, userID uuid.UUID) ([]Org, error) {
	rows, err := q.db.QueryContext(ctx, getOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Plan,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgPlan = `-- name: UpdateOrgPlan :exec
UPDATE orgs
SET plan = $1
WHERE id = $2
`

type UpdateOrgPlanParams struct {
	Plan  string    `json:"plan"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateOrgPlan(ctx context.Context, arg UpdateOrgPlanParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgPlan, arg.Plan, arg.OrgID)
	return err
}
