// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countServices = `-- name: CountServices :one
SELECT COUNT(*) FROM services WHERE org_id = $1
`

func (q *Queries) CountServices(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServices, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (org_id, name, url, method, expected_status, interval_seconds, timeout_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, name, url, method, expected_status, interval_seconds, timeout_seconds, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	Name            string    `json:"name"`
	Url             string    `json:"url"`
	Method          string    `json:"method"`
	ExpectedStatus  int32     `json:"expected_status"`
	IntervalSeconds int32     `json:"interval_seconds"`
	TimeoutSeconds  int32     `json:"timeout_seconds"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.OrgID,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.ExpectedStatus,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.ExpectedStatus,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1 AND org_id = $2
`

type DeleteServiceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.ExecContext(ctx, deleteService, arg.ID, arg.OrgID)
	return err
}

const getService = `-- name: GetService :one
SELECT id, org_id, name, url, method, expected_status, interval_seconds, timeout_seconds, is_active, created_at, updated_at
FROM services
WHERE id = $1 AND org_id = $2
`

type GetServiceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetService(ctx context.Context, arg GetServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, arg.ID, arg.OrgID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.ExpectedStatus,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, org_id, name, url, method, expected_status, interval_seconds, timeout_seconds, is_active, created_at, updated_at
FROM services
WHERE is_active = true
ORDER BY org_id, id
`

// used by worker (service role) — no org_id filter intentional
func (q *Queries) ListActiveServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.ExpectedStatus,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, org_id, name, url, method, expected_status, interval_seconds, timeout_seconds, is_active, created_at, updated_at
FROM services
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServices(ctx context.Context, orgID uuid.UUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.ExpectedStatus,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name             = $1,
    url              = $2,
    method           = $3,
    expected_status  = $4,
    interval_seconds = $5,
    timeout_seconds  = $6,
    is_active        = $7
WHERE id = $8 AND org_id = $9
RETURNING id, org_id, name, url, method, expected_status, interval_seconds, timeout_seconds, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	Name            string    `json:"name"`
	Url             string    `json:"url"`
	Method          string    `json:"method"`
	ExpectedStatus  int32     `json:"expected_status"`
	IntervalSeconds int32     `json:"interval_seconds"`
	TimeoutSeconds  int32     `json:"timeout_seconds"`
	IsActive        bool      `json:"is_active"`
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, updateService,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.ExpectedStatus,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.IsActive,
		arg.ID,
		arg.OrgID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.ExpectedStatus,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
