// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getServiceDailyUptime = `-- name: GetServiceDailyUptime :many
SELECT
    (checked_at AT TIME ZONE 'UTC')::date AS day,
    COUNT(*) FILTER (WHERE ok)            AS ok_count,
    COUNT(*)                              AS total_count
FROM check_results
WHERE service_id = $1
  AND checked_at >= NOW() - INTERVAL '90 days'
GROUP BY 1
ORDER BY 1 ASC
`

type GetServiceDailyUptimeRow struct {
	Day        time.Time `json:"day"`
	OkCount    int64     `json:"ok_count"`
	TotalCount int64     `json:"total_count"`
}

// One row per calendar day in the last 90 days that has at least one check.
// Missing days are filled in Go.
func (q *Queries) GetServiceDailyUptime(ctx context.Context, serviceID uuid.UUID) ([]GetServiceDailyUptimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getServiceDailyUptime, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServiceDailyUptimeRow
	for rows.Next() {
		var i GetServiceDailyUptimeRow
		if err := rows.Scan(&i.Day, &i.OkCount, &i.TotalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceLastCheck = `-- name: GetServiceLastCheck :one
SELECT ok, status_code, response_ms, checked_at
FROM check_results
WHERE service_id = $1
ORDER BY checked_at DESC
LIMIT 1
`

type GetServiceLastCheckRow struct {
	Ok         bool          `json:"ok"`
	StatusCode sql.NullInt32 `json:"status_code"`
	ResponseMs sql.NullInt32 `json:"response_ms"`
	CheckedAt  time.Time     `json:"checked_at"`
}

// Most recent check result for a service.
func (q *Queries) GetServiceLastCheck(ctx context.Context, serviceID uuid.UUID) (GetServiceLastCheckRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceLastCheck, serviceID)
	var i GetServiceLastCheckRow
	err := row.Scan(
		&i.Ok,
		&i.StatusCode,
		&i.ResponseMs,
		&i.CheckedAt,
	)
	return i, err
}

const getServiceUptime30d = `-- name: GetServiceUptime30d :one
SELECT
    COALESCE(
        COUNT(*) FILTER (WHERE ok) * 100.0 / NULLIF(COUNT(*), 0),
        0
    )::float8 AS uptime_percent
FROM check_results
WHERE service_id = $1
  AND checked_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetServiceUptime30d(ctx context.Context, serviceID uuid.UUID) (float64, error) {
	row := q.db.QueryRowContext(ctx, getServiceUptime30d, serviceID)
	var uptime_percent float64
	err := row.Scan(&uptime_percent)
	return uptime_percent, err
}

const listIncidentUpdatesByIncident = `-- name: ListIncidentUpdatesByIncident :many
SELECT id, incident_id, status, body, created_at
FROM incident_updates
WHERE incident_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListIncidentUpdatesByIncident(ctx context.Context, incidentID uuid.UUID) ([]IncidentUpdate, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentUpdatesByIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentUpdate
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicIncidents = `-- name: ListPublicIncidents :many
SELECT id, title, status, severity, started_at, resolved_at
FROM incidents
WHERE org_id = $1
  AND (
      status != 'resolved'
      OR resolved_at >= NOW() - INTERVAL '7 days'
  )
ORDER BY started_at DESC
LIMIT 10
`

type ListPublicIncidentsRow struct {
	ID         uuid.UUID    `json:"id"`
	Title      string       `json:"title"`
	Status     string       `json:"status"`
	Severity   string       `json:"severity"`
	StartedAt  time.Time    `json:"started_at"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
}

// Open incidents + last 5 resolved, ordered newest first.
func (q *Queries) ListPublicIncidents(ctx context.Context, orgID uuid.UUID) ([]ListPublicIncidentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicIncidents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicIncidentsRow
	for rows.Next() {
		var i ListPublicIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicServices = `-- name: ListPublicServices :many

SELECT id, name, url
FROM services
WHERE org_id = $1
  AND is_active = true
ORDER BY name
`

type ListPublicServicesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Url  string    `json:"url"`
}

// Public status page queries — service role, RLS bypassed.
// Every query filters explicitly by org_id.
// Only active services, no internal fields (org_id not in SELECT).
func (q *Queries) ListPublicServices(ctx context.Context, orgID uuid.UUID) ([]ListPublicServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicServices, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicServicesRow
	for rows.Next() {
		var i ListPublicServicesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
